<?php

/***************************************************************
 * Extension Manager/Repository config file for ext "imagemap_wizard".
 *
 * Auto generated by Extension Builder 2017-07-28 (classic version: 18-04-2012 20:12)
 *
 * Manual updates:
 * Only the data in the array - everything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Imagemap Wizard',
	'description' => 'Provides an TYPO3 Wizard which enables interactive Imagemap-Creation - related to the TYPO3-Linkwizard.',
	'category' => 'be',
	# 'shy' => 0,
	'version' => '7.0.0', // @TODO: test to apply the right TYPO3 Version
	'dependencies' => '',
	# 'conflicts' => '',
	# 'priority' => '',
	# 'loadOrder' => '',
	# 'module' => '',
	'state' => 'stable',
	'uploadfolder' => 0,
	'createDirs' => '',
	# 'modify_tables' => 'tt_content',
	'clearcacheonload' => TRUE,
	# 'lockType' => '',
	'author' => 'Tolleiv Nietsch, David Bruchmann',
	'author_email' => '??, david.bruchmann@gmail.com',
	'author_company' => '??, Webdevelopment Barlian',
	# 'CGLcompliance' => '',
	# 'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
            'typo3' => '7.0.0-7.6.99', // @TODO: test to apply the right TYPO3 Versions
			# 'cms' => '0.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'css_styled_content' => '0.0.0',
			'fluid_styled_content' => '0.0.0',
		),
	),
	'_md5_values_when_last_written' => '',
);
